name: Dependency Check

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch: # Allow manual trigger

jobs:
  dependency-check:
    name: Check Dependencies
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: nexium-resume-tailor/package-lock.json
        
    - name: Install dependencies
      run: |
        cd nexium-resume-tailor
        npm ci
        
    - name: Check for outdated packages
      run: |
        cd nexium-resume-tailor
        npm outdated || true
        
    - name: Audit dependencies
      run: |
        cd nexium-resume-tailor
        npm audit --audit-level=moderate
      continue-on-error: true
        
    - name: Check for security vulnerabilities
      run: |
        cd nexium-resume-tailor
        npm audit --audit-level=high
      continue-on-error: true
